### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by sf2020-LATTE** [sf2020-LATTE/chat-space#12]
# IPアドレス  
http://54.95.17.12/

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○グループ編集を行う際、参加しているチャットメンバー全員が表示されるようにしましょう。**

**＜チャットメンバー＞**
（太郎　と　 tech@a0r413214）
<img width="1099" alt="スクリーンショット 2020-08-10 10 28 47" src="https://user-images.githubusercontent.com/65144927/89746385-4d2ea780-daf4-11ea-96cf-7693b78113d2.png">


**＜グループ編集ページでは太郎しか表示されていない＞**
<img width="1099" alt="スクリーンショット 2020-08-10 10 25 19" src="https://user-images.githubusercontent.com/65144927/89746399-67688580-daf4-11ea-9843-ab4ff468ea73.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by sf2020-LATTE** [comment]
確認ありがとうございます。修正再デプロイしました。確認お願いします。

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。

**Comment by sf2020-LATTE** [comment]
ご確認ありがとうございました。今後もよろしくお願いします。
